# src/main/resources/application-prod.yml

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_analytics}
    username: ${DATABASE_USER:finance_user}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  logging:
    level:
      de.finance.analytics: INFO
      org.springframework.web: WARN
      org.hibernate: WARN
      root: INFO

server:
  port: ${PORT:8080}
