-- 🧪 H2 Test Database Schema for Banking Project
-- Lightweight in-memory database for unit and integration tests

-- H2 compatible schema (slightly different syntax from PostgreSQL)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    color_hex VARCHAR(7) DEFAULT '#6C5CE7',
    icon VARCHAR(10),
    parent_category_id BIGINT,
    keywords CLOB,
    is_expense BOOLEAN DEFAULT true,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_category_id) REFERENCES categories(id)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR(100) NOT NULL,
    account_number VARCHAR(50),
    booking_date DATE NOT NULL,
    value_date DATE,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'EUR',
    reference VARCHAR(500),
    counterparty VARCHAR(200),
    category_id BIGINT,
    processing_state VARCHAR(20) DEFAULT 'PENDING',
    import_source VARCHAR(20),
    import_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    raw_data CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    CHECK (transaction_type IN ('DEBIT', 'CREDIT')),
    CHECK (processing_state IN ('PENDING', 'PROCESSED', 'FAILED', 'CANCELLED'))
);

-- Indexes for H2 (simpler syntax)
CREATE INDEX idx_transactions_booking_date ON transactions(booking_date);
CREATE INDEX idx_transactions_bank_name ON transactions(bank_name);
CREATE INDEX idx_transactions_type ON transactions(transaction_type);
CREATE INDEX idx_transactions_category ON transactions(category_id);
CREATE INDEX idx_transactions_state ON transactions(processing_state);